receivers:
  # Azure Event Hub Receiver
#  azureeventhub/metrics:
#    connection: Endpoint=sb://signoz-metrics.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=;EntityPath=metrics
#    partition: ""
#    group: "$Default"
#    format: "azure"  # Important: Use 'azure' format for Azure Monitor data

  azureeventhub/logs:
    connection: Endpoint=sb://signoz-integration.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=xxx;EntityPath=logs
    group: "$Default"
    format: "azure"  # Important: Use 'azure' format for Azure Monitor data

  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  debug:
    verbosity: detailed

  # SigNoz exporter
  otlp/signoz:
    endpoint: "ingest.us.staging.signoz.cloud:443"
    headers:
      "signoz-ingestion-key": f43f70bd-5ea1-478a-9db8-39ddb1e13b4c
    tls:
      insecure: false
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

service:
  pipelines:
    logs:
      receivers: [ azureeventhub/logs ]
      exporters: [ otlp/signoz, debug ]
  telemetry:
    logs:
      level: debug